# Generated by Django 4.2.11 on 2026-08-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_otp_code_customuser_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('treasurer', 'Treasurer'), ('staff', 'Staff'), ('farmer', 'Farmer')], default='farmer', max_length=10),
        ),
    ]
