# Generated by Django 6.0.2 on 2026-02-14 19:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(help_text='National ID/Passport number', max_length=20, unique=True)),
                ('phone_number', models.CharField(help_text='Required for SMS notifications', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+254XXXXXXXXX' or '07XXXXXXXX'", regex='\\+?254?\\d{9,12}$')])),
                ('alt_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('region', models.CharField(choices=[('central', 'Central'), ('eastern', 'Eastern'), ('western', 'Western'), ('rift_valley', 'Rift Valley'), ('coast', 'Coast'), ('nairobi', 'Nairobi'), ('north_eastern', 'North Eastern'), ('nyanza', 'Nyanza')], max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('farm_name', models.CharField(max_length=200)),
                ('farm_size_acres', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('coffee_varieties', models.TextField(help_text='List varieties grown (e.g., SL28, Ruiru 11, Batian, K7)')),
                ('years_farming', models.IntegerField(default=1)),
                ('sms_notifications', models.BooleanField(default=True, help_text='Receive SMS for deliveries and payments')),
                ('sms_language', models.CharField(choices=[('en', 'English'), ('sw', 'Kiswahili')], default='en', max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('mobile_money_number', models.CharField(blank=True, help_text='M-Pesa/Airtel Money number', max_length=15)),
                ('mobile_money_provider', models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('telkom', 'Telkom T-Cash')], max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_farmers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registration_date'],
                'indexes': [models.Index(fields=['phone_number'], name='farmers_far_phone_n_974cc5_idx'), models.Index(fields=['national_id'], name='farmers_far_nationa_825564_idx'), models.Index(fields=['region', 'district'], name='farmers_far_region_c390cc_idx')],
            },
        ),
    ]
