# Generated by Django 4.2.11 on 2026-05-08 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='For demographic reporting', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='phone_number',
            field=models.CharField(help_text='Required for SMS notifications', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+254XXXXXXXXX' or '07XXXXXXXX'", regex='^\\+?254?\\d{9,12}$')]),
        ),
    ]
