# Generated by Django 4.2.11 on 2026-07-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_farmerprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='farmer_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
