# Generated by Django 6.0.2 on 2026-02-14 19:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('cherry_weight_kg', models.DecimalField(decimal_places=2, help_text='Weight of coffee cherry in kilograms', max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('dry_weight_kg', models.DecimalField(decimal_places=2, editable=False, help_text='5kg cherry = 1kg dry coffee (auto-calculated)', max_digits=10)),
                ('quality_grade', models.CharField(choices=[('specialty', 'Specialty (85-100)'), ('premium', 'Premium (80-84)'), ('standard', 'Standard (70-79)'), ('commercial', 'Commercial (below 70)')], default='standard', max_length=20)),
                ('cupping_score', models.IntegerField(blank=True, help_text='Score out of 100', null=True)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=120.0, help_text='Price per kg of dry coffee in KES', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, help_text='Auto-calculated: (cherry_weight_kg / 5) * price_per_kg', max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('sms_sent', models.BooleanField(default=False)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sms_status', models.CharField(blank=True, help_text='SMS delivery status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_batches', to='farmers.farmerprofile')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-delivery_date', '-created_at'],
                'indexes': [models.Index(fields=['farmer', 'delivery_date'], name='deliveries__farmer__0febc0_idx'), models.Index(fields=['payment_status'], name='deliveries__payment_232d7a_idx'), models.Index(fields=['batch_code'], name='deliveries__batch_c_cc6340_idx')],
            },
        ),
    ]
