# Generated by Django 6.0.2 on 2026-02-15 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('delivery_summary', 'Delivery Summary'), ('farmer_performance', 'Farmer Performance'), ('payment_analysis', 'Payment Analysis'), ('harvest_forecast', 'Harvest Forecast'), ('quality_analysis', 'Quality Analysis')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date_range', models.CharField(default='last_30_days', max_length=20)),
                ('custom_start_date', models.DateField(blank=True, null=True)),
                ('custom_end_date', models.DateField(blank=True, null=True)),
                ('chart_type', models.CharField(choices=[('bar', 'Bar'), ('line', 'Line'), ('pie', 'Pie'), ('area', 'Area')], default='bar', max_length=20)),
                ('chart_format', models.CharField(choices=[('chart', 'Chart'), ('table', 'Table'), ('both', 'Both')], default='both', max_length=10)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('group_by', models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('month', 'Month'), ('week', 'Week'), ('quality', 'Quality Grade'), ('region', 'Region')], max_length=50)),
                ('auto_export', models.BooleanField(default=False)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('pdf', 'PDF')], default='csv', max_length=10)),
                ('scheduled', models.BooleanField(default=False)),
                ('schedule_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/')),
                ('format', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='reports.reporttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('chart', 'Chart'), ('metric', 'Metric'), ('table', 'Table'), ('alert', 'Alert')], max_length=20)),
                ('row', models.IntegerField(default=1)),
                ('column', models.IntegerField(default=1)),
                ('width', models.IntegerField(default=6)),
                ('height', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20)),
                ('metric_field', models.CharField(blank=True, max_length=50)),
                ('color_scheme', models.CharField(default='default', max_length=20)),
                ('show_title', models.BooleanField(default=True)),
                ('refresh_interval', models.IntegerField(default=0, help_text='Refresh interval in seconds (0 for no refresh)')),
                ('is_visible', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
                ('report_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reporttemplate')),
            ],
            options={
                'ordering': ['row', 'column'],
            },
        ),
    ]
